language: java

script: mvn test -PnoServerTests

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - andrei.varabyeu@gmail.com
  flowdock: 01f9aad1fc42e06572aa09d1b49acccb

branches:
  only:
    - master